- hosts: bigip
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: 192.168.86.40
    ansible_user: admin
    ansible_httpapi_password: totallynotapassword
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Start declaration
      bigip_as3_deploy:
        content: "{{ lookup('file', 'ansible_declarepolicy2.json') }}"
    - name: SaveConfig
      bigip_config:
        save: yes
      register: task
